title: "Debayan's Dilemma"
description: "I'm a PhD student in fluvial geomorphology at FU Berlin, Germany. This is a blog about my geoscience + statistics journey. I try not to use AI when I write here."
theme: jekyll-theme-minimal
author: "Debayan Chatterjee"
