title: "Brown Noise"
description: "Hi, I'm Debayan, a PhD student in river geomorphology at FU Berlin, Germany. This is a blog about my geoscience + statistics journey. I try not to use AI when I write here."
theme: jekyll-theme-minimal
author: "Debayan Chatterjee"
