title: "Brown Noise"
description: "Hi, I'm Debayan, a PhD student in riverine geomorphology at FU Berlin. This blog is about my geoscience + statistics journey. I try not to use AI when I write here. <br> debayan.chatterjee@fu-berlin.de <br>"
theme: jekyll-theme-minimal
author: "Debayan Chatterjee"
logo: ProfPic.jpeg
